export const countries = [
  {
    id: 1,
    name_cn: '阿富汗',
    name_en: 'Afghanistan',
    name_en_complete: 'the Islamic Republic of Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    numeric: 4,
  },
  {
    id: 2,
    name_cn: '奥兰群岛',
    name_en: 'Aland Islands',
    name_en_complete: null,
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: 248,
    note: 'ISO 3166-1:2006新增',
  },
  {
    id: 3,
    name_cn: '阿尔巴尼亚',
    name_en: 'Albania',
    name_en_complete: 'the Republic of Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: 8,
  },
  {
    id: 4,
    name_cn: '阿尔及利亚',
    name_en: 'Algeria',
    name_en_complete: "the People's Democratic Republic of Algeria",
    alpha2: 'DZ',
    alpha3: 'DZA',
    numeric: 12,
  },
  {
    id: 5,
    name_cn: '美属萨摩亚',
    name_en: 'American Samoa',
    name_en_complete: null,
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: 16,
  },
  {
    id: 6,
    name_cn: '安道尔',
    name_en: 'Andorra',
    name_en_complete: 'the Principality of Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: 20,
  },
  {
    id: 7,
    name_cn: '安哥拉',
    name_en: 'Angola',
    name_en_complete: 'the Republic of Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: 24,
  },
  {
    id: 8,
    name_cn: '安圭拉',
    name_en: 'Anguilla',
    name_en_complete: null,
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: 660,
  },
  {
    id: 9,
    name_cn: '南极洲',
    name_en: 'Antarctica',
    name_en_complete: null,
    alpha2: 'AQ',
    alpha3: 'ATA',
    numeric: 10,
  },
  {
    id: 10,
    name_cn: '安提瓜和巴布达',
    name_en: 'Antigua and Barbuda',
    name_en_complete: null,
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: 28,
  },
  {
    id: 11,
    name_cn: '阿根廷',
    name_en: 'Argentina',
    name_en_complete: 'the Argentine Republic',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: 32,
  },
  {
    id: 12,
    name_cn: '亚美尼亚',
    name_en: 'Armenia',
    name_en_complete: 'the Republic of Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: 51,
  },
  {
    id: 13,
    name_cn: '阿鲁巴',
    name_en: 'Aruba',
    name_en_complete: null,
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: 533,
  },
  {
    id: 14,
    name_cn: '澳大利亚',
    name_en: 'Australia',
    name_en_complete: null,
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: 36,
  },
  {
    id: 15,
    name_cn: '奥地利',
    name_en: 'Austria',
    name_en_complete: 'the Republic of Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: 40,
  },
  {
    id: 16,
    name_cn: '阿塞拜疆',
    name_en: 'Azerbaijan',
    name_en_complete: 'the Republic of Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: 31,
  },
  {
    id: 17,
    name_cn: '巴哈马',
    name_en: 'Bahamas (The)',
    name_en_complete: 'the Commonwealth of The Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    numeric: 44,
  },
  {
    id: 18,
    name_cn: '巴林',
    name_en: 'Bahrain',
    name_en_complete: 'the Kingdom of Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    numeric: 48,
  },
  {
    id: 19,
    name_cn: '孟加拉国',
    name_en: 'Bangladesh',
    name_en_complete: "the People's Republic of Bangladesh",
    alpha2: 'BD',
    alpha3: 'BGD',
    numeric: 50,
  },
  {
    id: 20,
    name_cn: '巴巴多斯',
    name_en: 'Barbados',
    name_en_complete: null,
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: 52,
  },
  {
    id: 21,
    name_cn: '白俄罗斯',
    name_en: 'Belarus',
    name_en_complete: 'the Republic of Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: 112,
  },
  {
    id: 22,
    name_cn: '比利时',
    name_en: 'Belgium',
    name_en_complete: 'the Kingdom of Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: 56,
  },
  {
    id: 23,
    name_cn: '伯利兹',
    name_en: 'Belize',
    name_en_complete: null,
    alpha2: 'BZ',
    alpha3: 'BLZ',
    numeric: 84,
  },
  {
    id: 24,
    name_cn: '贝宁',
    name_en: 'Benin',
    name_en_complete: 'the Republic of Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    numeric: 204,
  },
  {
    id: 25,
    name_cn: '百慕大',
    name_en: 'Bermuda',
    name_en_complete: null,
    alpha2: 'BM',
    alpha3: 'BMU',
    numeric: 60,
  },
  {
    id: 26,
    name_cn: '不丹',
    name_en: 'Bhutan',
    name_en_complete: 'the Kingdom of Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    numeric: 64,
  },
  {
    id: 27,
    name_cn: '玻利维亚',
    name_en: 'Bolivia',
    name_en_complete: 'the Republic of Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    numeric: 68,
  },
  {
    id: 28,
    name_cn: '波黑',
    name_en: 'Bosnia and Herzegovina',
    name_en_complete: null,
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: 70,
  },
  {
    id: 29,
    name_cn: '博茨瓦纳',
    name_en: 'Botswana',
    name_en_complete: 'the Republic of Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    numeric: 72,
  },
  {
    id: 30,
    name_cn: '布维岛',
    name_en: 'Bouvet Island',
    name_en_complete: null,
    alpha2: 'BV',
    alpha3: 'BVT',
    numeric: 74,
  },
  {
    id: 31,
    name_cn: '巴西',
    name_en: 'Brazil',
    name_en_complete: 'the Federative Republic of Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    numeric: 76,
  },
  {
    id: 32,
    name_cn: '英属印度洋领地',
    name_en: 'British Indian Ocean Territory (the)',
    name_en_complete: null,
    alpha2: 'IO',
    alpha3: 'IOT',
    numeric: 86,
  },
  {
    id: 33,
    name_cn: '文莱',
    name_en: 'Brunei Darussalam',
    name_en_complete: null,
    alpha2: 'BN',
    alpha3: 'BRN',
    numeric: 96,
  },
  {
    id: 34,
    name_cn: '保加利亚',
    name_en: 'Bulgaria',
    name_en_complete: 'the Republic of Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: 100,
  },
  {
    id: 35,
    name_cn: '布基纳法索',
    name_en: 'Burkina Faso',
    name_en_complete: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    numeric: 854,
  },
  {
    id: 36,
    name_cn: '布隆迪',
    name_en: 'Burundi',
    name_en_complete: 'the Republic of Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    numeric: 108,
  },
  {
    id: 37,
    name_cn: '柬埔寨',
    name_en: 'Cambodia',
    name_en_complete: 'the Kingdom of Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    numeric: 116,
  },
  {
    id: 38,
    name_cn: '喀麦隆',
    name_en: 'Cameroon',
    name_en_complete: 'the Republic of Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    numeric: 120,
  },
  {
    id: 39,
    name_cn: '加拿大',
    name_en: 'Canada',
    name_en_complete: null,
    alpha2: 'CA',
    alpha3: 'CAN',
    numeric: 124,
  },
  {
    id: 40,
    name_cn: '佛得角',
    name_en: 'Cape Verde',
    name_en_complete: 'the Republic of Cape Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    numeric: 132,
  },
  {
    id: 41,
    name_cn: '开曼群岛',
    name_en: 'Cayman Islands (the)',
    name_en_complete: null,
    alpha2: 'KY',
    alpha3: 'CYM',
    numeric: 136,
  },
  {
    id: 42,
    name_cn: '中非',
    name_en: 'Central African Republic (the)',
    name_en_complete: 'the Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    numeric: 140,
  },
  {
    id: 43,
    name_cn: '乍得',
    name_en: 'Chad',
    name_en_complete: 'the Republic of Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    numeric: 148,
  },
  {
    id: 44,
    name_cn: '智利',
    name_en: 'Chile',
    name_en_complete: 'the Republic of Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    numeric: 152,
  },
  {
    id: 45,
    name_cn: '中国',
    name_en: 'China',
    name_en_complete: "the People's Republic of China",
    alpha2: 'CN',
    alpha3: 'CHN',
    numeric: 156,
  },
  {
    id: 46,
    name_cn: '圣诞岛',
    name_en: 'Christmas Island',
    name_en_complete: null,
    alpha2: 'CX',
    alpha3: 'CXR',
    numeric: 162,
  },
  {
    id: 47,
    name_cn: '科科斯（基林）群岛',
    name_en: 'Cocos (Keeling) Islands (the)',
    name_en_complete: null,
    alpha2: 'CC',
    alpha3: 'CCK',
    numeric: 166,
  },
  {
    id: 48,
    name_cn: '哥伦比亚',
    name_en: 'Colombia',
    name_en_complete: 'the Republic of Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    numeric: 170,
  },
  {
    id: 49,
    name_cn: '科摩罗',
    name_en: 'Comoros',
    name_en_complete: 'the Union of the Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    numeric: 174,
  },
  {
    id: 50,
    name_cn: '刚果（布）',
    name_en: 'Congo',
    name_en_complete: 'the Republic of the Congo',
    alpha2: 'CG',
    alpha3: 'COG',
    numeric: 178,
  },
  {
    id: 51,
    name_cn: '刚果（金）',
    name_en: 'Congo (the Democratic Republic of the)',
    name_en_complete: 'the Democratic Republic of the Congo',
    alpha2: 'CD',
    alpha3: 'COD',
    numeric: 180,
  },
  {
    id: 52,
    name_cn: '库克群岛',
    name_en: 'Cook Islands (the)',
    name_en_complete: null,
    alpha2: 'CK',
    alpha3: 'COK',
    numeric: 184,
  },
  {
    id: 53,
    name_cn: '哥斯达黎加',
    name_en: 'Costa Rica',
    name_en_complete: 'the Republic of Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    numeric: 188,
  },
  {
    id: 54,
    name_cn: '科特迪瓦',
    name_en: "Côte d'Ivoire",
    name_en_complete: "the Republic of Côte d'Ivoire",
    alpha2: 'CI',
    alpha3: 'CIV',
    numeric: 384,
  },
  {
    id: 55,
    name_cn: '克罗地亚',
    name_en: 'Croatia',
    name_en_complete: 'the Republic of Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    numeric: 191,
  },
  {
    id: 56,
    name_cn: '古巴',
    name_en: 'Cuba',
    name_en_complete: 'the Republic of Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    numeric: 192,
  },
  {
    id: 57,
    name_cn: '塞浦路斯',
    name_en: 'Cyprus',
    name_en_complete: 'the Republic of Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    numeric: 196,
  },
  {
    id: 58,
    name_cn: '捷克',
    name_en: 'Czech Republic (the)',
    name_en_complete: 'the Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    numeric: 203,
  },
  {
    id: 59,
    name_cn: '丹麦',
    name_en: 'Denmark',
    name_en_complete: 'the Kingdom of Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    numeric: 208,
  },
  {
    id: 60,
    name_cn: '吉布提',
    name_en: 'Djibouti',
    name_en_complete: 'the Republic of Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    numeric: 262,
  },
  {
    id: 61,
    name_cn: '多米尼克',
    name_en: 'Dominica',
    name_en_complete: 'the Commonwealth of Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    numeric: 212,
  },
  {
    id: 62,
    name_cn: '多米尼加',
    name_en: 'Dominican Republic (the)',
    name_en_complete: 'the Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    numeric: 214,
  },
  {
    id: 63,
    name_cn: '厄瓜多尔',
    name_en: 'Ecuador',
    name_en_complete: 'the Republic of Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    numeric: 218,
  },
  {
    id: 64,
    name_cn: '埃及',
    name_en: 'Egypt',
    name_en_complete: 'the Arab Republic of Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    numeric: 818,
  },
  {
    id: 65,
    name_cn: '萨尔瓦多',
    name_en: 'El Salvador',
    name_en_complete: 'the Republic of El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    numeric: 222,
  },
  {
    id: 66,
    name_cn: '赤道几内亚',
    name_en: 'Equatorial Guinea',
    name_en_complete: 'the Republic of Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    numeric: 226,
  },
  {
    id: 67,
    name_cn: '厄立特里亚',
    name_en: 'Eritrea',
    name_en_complete: null,
    alpha2: 'ER',
    alpha3: 'ERI',
    numeric: 232,
  },
  {
    id: 68,
    name_cn: '爱沙尼亚',
    name_en: 'Estonia',
    name_en_complete: 'the Republic of Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    numeric: 233,
  },
  {
    id: 69,
    name_cn: '埃塞俄比亚',
    name_en: 'Ethiopia',
    name_en_complete: 'the Federal Democratic Republic of Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    numeric: 231,
  },
  {
    id: 70,
    name_cn: '福克兰群岛（马尔维纳斯）',
    name_en: 'Falkland Islands (the) [Malvinas]',
    name_en_complete: null,
    alpha2: 'FK',
    alpha3: 'FLK',
    numeric: 238,
  },
  {
    id: 71,
    name_cn: '法罗群岛',
    name_en: 'Faroe Islands (the)',
    name_en_complete: null,
    alpha2: 'FO',
    alpha3: 'FRO',
    numeric: 234,
  },
  {
    id: 72,
    name_cn: '斐济',
    name_en: 'Fiji',
    name_en_complete: 'the Republic of the Fiji Islands',
    alpha2: 'FJ',
    alpha3: 'FJI',
    numeric: 242,
  },
  {
    id: 73,
    name_cn: '芬兰',
    name_en: 'Finland',
    name_en_complete: 'the Republic of Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    numeric: 246,
  },
  {
    id: 74,
    name_cn: '法国',
    name_en: 'France',
    name_en_complete: 'the French Republic',
    alpha2: 'FR',
    alpha3: 'FRA',
    numeric: 250,
  },
  {
    id: 75,
    name_cn: '法属圭亚那',
    name_en: 'French Guiana',
    name_en_complete: null,
    alpha2: 'GF',
    alpha3: 'GUF',
    numeric: 254,
  },
  {
    id: 76,
    name_cn: '法属波利尼西亚',
    name_en: 'French Polynesia',
    name_en_complete: null,
    alpha2: 'PF',
    alpha3: 'PYF',
    numeric: 258,
  },
  {
    id: 77,
    name_cn: '法属南部领地',
    name_en: 'French Southern Territories (the)',
    name_en_complete: null,
    alpha2: 'TF',
    alpha3: 'ATF',
    numeric: 260,
  },
  {
    id: 78,
    name_cn: '加蓬',
    name_en: 'Gabon',
    name_en_complete: 'the Gabonese Republic',
    alpha2: 'GA',
    alpha3: 'GAB',
    numeric: 266,
  },
  {
    id: 79,
    name_cn: '冈比亚',
    name_en: 'Gambia (The)',
    name_en_complete: 'the Republic of The Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    numeric: 270,
  },
  {
    id: 80,
    name_cn: '格鲁吉亚',
    name_en: 'Georgia',
    name_en_complete: null,
    alpha2: 'GE',
    alpha3: 'GEO',
    numeric: 268,
  },
  {
    id: 81,
    name_cn: '德国',
    name_en: 'Germany',
    name_en_complete: 'he Federal Republic of Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    numeric: 276,
  },
  {
    id: 82,
    name_cn: '加纳',
    name_en: 'Ghana',
    name_en_complete: 'the Republic of Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    numeric: 288,
  },
  {
    id: 83,
    name_cn: '直布罗陀',
    name_en: 'Gibraltar',
    name_en_complete: null,
    alpha2: 'GI',
    alpha3: 'GIB',
    numeric: 292,
  },
  {
    id: 84,
    name_cn: '希腊',
    name_en: 'Greece',
    name_en_complete: 'the Hellenic Republic',
    alpha2: 'GR',
    alpha3: 'GRC',
    numeric: 300,
  },
  {
    id: 85,
    name_cn: '格陵兰',
    name_en: 'Greenland',
    name_en_complete: null,
    alpha2: 'GL',
    alpha3: 'GRL',
    numeric: 304,
  },
  {
    id: 86,
    name_cn: '格林纳达',
    name_en: 'Grenada',
    name_en_complete: null,
    alpha2: 'GD',
    alpha3: 'GRD',
    numeric: 308,
  },
  {
    id: 87,
    name_cn: '瓜德罗普',
    name_en: 'Guadeloupe',
    name_en_complete: null,
    alpha2: 'GP',
    alpha3: 'GLP',
    numeric: 312,
  },
  {
    id: 88,
    name_cn: '关岛',
    name_en: 'Guam',
    name_en_complete: null,
    alpha2: 'GU',
    alpha3: 'GUM',
    numeric: 316,
  },
  {
    id: 89,
    name_cn: '危地马拉',
    name_en: 'Guatemala',
    name_en_complete: 'the Republic of Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    numeric: 320,
  },
  {
    id: 90,
    name_cn: '格恩西岛',
    name_en: 'Guernsey',
    name_en_complete: null,
    alpha2: 'GG',
    alpha3: 'GGY',
    numeric: 831,
    note: 'ISO 3166-1:2006新增',
  },
  {
    id: 91,
    name_cn: '几内亚',
    name_en: 'Guinea',
    name_en_complete: 'the Republic of Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    numeric: 324,
  },
  {
    id: 92,
    name_cn: '几内亚比绍',
    name_en: 'Guinea-Bissau',
    name_en_complete: 'the Republic of Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    numeric: 624,
  },
  {
    id: 93,
    name_cn: '圭亚那',
    name_en: 'Guyana',
    name_en_complete: 'the Republic of Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    numeric: 328,
  },
  {
    id: 94,
    name_cn: '海地',
    name_en: 'Haiti',
    name_en_complete: 'the Republic of Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    numeric: 332,
  },
  {
    id: 95,
    name_cn: '赫德岛和麦克唐纳岛',
    name_en: 'Heard Island and McDonald Islands',
    name_en_complete: null,
    alpha2: 'HM',
    alpha3: 'HMD',
    numeric: 334,
  },
  {
    id: 96,
    name_cn: '梵蒂冈',
    name_en: 'Holy See (the) [Vatican City State]',
    name_en_complete: null,
    alpha2: 'VA',
    alpha3: 'VAT',
    numeric: 336,
    note: 'ISO 3166.1:2006调整英文名称，代码未变',
  },
  {
    id: 97,
    name_cn: '洪都拉斯',
    name_en: 'Honduras',
    name_en_complete: 'the Republic of Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    numeric: 340,
  },
  {
    id: 98,
    name_cn: '香港',
    name_en: 'Hong Kong',
    name_en_complete: 'the Hong Kong Special Administrative Region of China',
    alpha2: 'HK',
    alpha3: 'HKG',
    numeric: 344,
  },
  {
    id: 99,
    name_cn: '匈牙利',
    name_en: 'Hungary',
    name_en_complete: 'the Republic of Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    numeric: 348,
  },
  {
    id: 100,
    name_cn: '冰岛',
    name_en: 'Iceland',
    name_en_complete: 'the Republic of Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    numeric: 352,
  },
  {
    id: 101,
    name_cn: '印度',
    name_en: 'India',
    name_en_complete: 'the Republic of India',
    alpha2: 'IN',
    alpha3: 'IND',
    numeric: 356,
  },
  {
    id: 102,
    name_cn: '印度尼西亚',
    name_en: 'Indonesia',
    name_en_complete: 'the Republic of Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    numeric: 360,
  },
  {
    id: 103,
    name_cn: '伊朗',
    name_en: 'Iran (the Islamic Republic of)',
    name_en_complete: 'the Islamic Republic of Iran',
    alpha2: 'IR',
    alpha3: 'IRN',
    numeric: 364,
  },
  {
    id: 104,
    name_cn: '伊拉克',
    name_en: 'Iraq',
    name_en_complete: 'the Republic of Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    numeric: 368,
  },
  {
    id: 105,
    name_cn: '爱尔兰',
    name_en: 'Ireland',
    name_en_complete: null,
    alpha2: 'IE',
    alpha3: 'IRL',
    numeric: 372,
  },
  {
    id: 106,
    name_cn: '英国属地曼岛',
    name_en: 'Isle of Man',
    name_en_complete: null,
    alpha2: 'IM',
    alpha3: 'IMN',
    numeric: 833,
    note: 'ISO 3166-1:2006新增',
  },
  {
    id: 107,
    name_cn: '以色列',
    name_en: 'Israel',
    name_en_complete: 'the State of Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    numeric: 376,
  },
  {
    id: 108,
    name_cn: '意大利',
    name_en: 'Italy',
    name_en_complete: 'the Republic of Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    numeric: 380,
  },
  {
    id: 109,
    name_cn: '牙买加',
    name_en: 'Jamaica',
    name_en_complete: null,
    alpha2: 'JM',
    alpha3: 'JAM',
    numeric: 388,
  },
  {
    id: 110,
    name_cn: '日本',
    name_en: 'Japan',
    name_en_complete: null,
    alpha2: 'JP',
    alpha3: 'JPN',
    numeric: 392,
  },
  {
    id: 111,
    name_cn: '泽西岛',
    name_en: 'Jersey',
    name_en_complete: null,
    alpha2: 'JE',
    alpha3: 'JEY',
    numeric: 832,
    note: 'ISO 3166-1:2006新增',
  },
  {
    id: 112,
    name_cn: '约旦',
    name_en: 'Jordan',
    name_en_complete: 'the Hashemite Kingdom of Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    numeric: 400,
  },
  {
    id: 113,
    name_cn: '哈萨克斯坦',
    name_en: 'Kazakhstan',
    name_en_complete: 'the Republic of Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    numeric: 398,
  },
  {
    id: 114,
    name_cn: '肯尼亚',
    name_en: 'Kenya',
    name_en_complete: 'the Republic of Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    numeric: 404,
  },
  {
    id: 115,
    name_cn: '基里巴斯',
    name_en: 'Kiribati',
    name_en_complete: 'the Republic of Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    numeric: 296,
  },
  {
    id: 116,
    name_cn: '朝鲜',
    name_en: "Korea (the Democratic People's Republic of)",
    name_en_complete: "the Democratic People's Republic of Korea",
    alpha2: 'KP',
    alpha3: 'PRK',
    numeric: 408,
  },
  {
    id: 117,
    name_cn: '韩国',
    name_en: 'Korea (the Republic of)',
    name_en_complete: 'the Republic of Korea',
    alpha2: 'KR',
    alpha3: 'KOR',
    numeric: 410,
  },
  {
    id: 118,
    name_cn: '科威特',
    name_en: 'Kuwait',
    name_en_complete: 'he State of Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    numeric: 414,
  },
  {
    id: 119,
    name_cn: '吉尔吉斯斯坦',
    name_en: 'Kyrgyzstan',
    name_en_complete: 'the Kyrgyz Republic',
    alpha2: 'KG',
    alpha3: 'KGZ',
    numeric: 417,
  },
  {
    id: 120,
    name_cn: '老挝',
    name_en: "Lao People's Democratic Republic (the)",
    name_en_complete: "the Lao People's Democratic Republic",
    alpha2: 'LA',
    alpha3: 'LAO',
    numeric: 418,
  },
  {
    id: 121,
    name_cn: '拉脱维亚',
    name_en: 'Latvia',
    name_en_complete: 'the Republic of Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    numeric: 428,
  },
  {
    id: 122,
    name_cn: '黎巴嫩',
    name_en: 'Lebanon',
    name_en_complete: 'the Lebanese Republic',
    alpha2: 'LB',
    alpha3: 'LBN',
    numeric: 422,
  },
  {
    id: 123,
    name_cn: '莱索托',
    name_en: 'Lesotho',
    name_en_complete: 'the Kingdom of Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    numeric: 426,
  },
  {
    id: 124,
    name_cn: '利比里亚',
    name_en: 'Liberia',
    name_en_complete: 'the Republic of Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    numeric: 430,
  },
  {
    id: 125,
    name_cn: '利比亚',
    name_en: 'Libyan Arab Jamahiriya (the)',
    name_en_complete: "the Socialist People's Libyan Arab Jamahiriya",
    alpha2: 'LY',
    alpha3: 'LBY',
    numeric: 434,
  },
  {
    id: 126,
    name_cn: '列支敦士登',
    name_en: 'Liechtenstein',
    name_en_complete: 'the Principality of Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    numeric: 438,
  },
  {
    id: 127,
    name_cn: '立陶宛',
    name_en: 'Lithuania',
    name_en_complete: 'the Republic of Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    numeric: 440,
  },
  {
    id: 128,
    name_cn: '卢森堡',
    name_en: 'Luxembourg',
    name_en_complete: 'the Grand Duchy of Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    numeric: 442,
  },
  {
    id: 129,
    name_cn: '澳门',
    name_en: 'Macao',
    name_en_complete: 'Macao Special Administrative Region of China',
    alpha2: 'MO',
    alpha3: 'MAC',
    numeric: 446,
  },
  {
    id: 130,
    name_cn: '前南马其顿',
    name_en: 'Macedonia (the former Yugoslav Republic of)',
    name_en_complete: 'the former Yugoslav Republic of Macedonia',
    alpha2: 'MK',
    alpha3: 'MKD',
    numeric: 807,
  },
  {
    id: 131,
    name_cn: '马达加斯加',
    name_en: 'Madagascar',
    name_en_complete: 'the Republic of Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    numeric: 450,
  },
  {
    id: 132,
    name_cn: '马拉维',
    name_en: 'Malawi',
    name_en_complete: 'the Republic of Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    numeric: 454,
  },
  {
    id: 133,
    name_cn: '马来西亚',
    name_en: 'Malaysia',
    name_en_complete: null,
    alpha2: 'MY',
    alpha3: 'MYS',
    numeric: 458,
  },
  {
    id: 134,
    name_cn: '马尔代夫',
    name_en: 'Maldives',
    name_en_complete: 'the Republic of Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    numeric: 462,
  },
  {
    id: 135,
    name_cn: '马里',
    name_en: 'Mali',
    name_en_complete: 'the Republic of Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    numeric: 466,
  },
  {
    id: 136,
    name_cn: '马耳他',
    name_en: 'Malta',
    name_en_complete: 'the Republic of Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    numeric: 470,
  },
  {
    id: 137,
    name_cn: '马绍尔群岛',
    name_en: 'Marshall Islands (the)',
    name_en_complete: 'the Republic of the Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    numeric: 584,
  },
  {
    id: 138,
    name_cn: '马提尼克',
    name_en: 'Martinique',
    name_en_complete: null,
    alpha2: 'MQ',
    alpha3: 'MTQ',
    numeric: 474,
  },
  {
    id: 139,
    name_cn: '毛利塔尼亚',
    name_en: 'Mauritania',
    name_en_complete: 'the Islamic Republic of Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    numeric: 478,
  },
  {
    id: 140,
    name_cn: '毛里求斯',
    name_en: 'Mauritius',
    name_en_complete: 'the Republic of Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    numeric: 480,
  },
  {
    id: 141,
    name_cn: '马约特',
    name_en: 'Mayotte',
    name_en_complete: null,
    alpha2: 'YT',
    alpha3: 'MYT',
    numeric: 175,
  },
  {
    id: 142,
    name_cn: '墨西哥',
    name_en: 'Mexico',
    name_en_complete: 'the United Mexican States',
    alpha2: 'MX',
    alpha3: 'MEX',
    numeric: 484,
  },
  {
    id: 143,
    name_cn: '密克罗尼西亚联邦',
    name_en: 'Micronesia (the Federated States of)',
    name_en_complete: 'the Federated States of Micronesia',
    alpha2: 'FM',
    alpha3: 'FSM',
    numeric: 583,
  },
  {
    id: 144,
    name_cn: '摩尔多瓦',
    name_en: 'Moldova (the Republic of)',
    name_en_complete: 'the Republic of Moldova',
    alpha2: 'MD',
    alpha3: 'MDA',
    numeric: 498,
  },
  {
    id: 145,
    name_cn: '摩纳哥',
    name_en: 'Monaco',
    name_en_complete: 'the Principality of Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    numeric: 492,
  },
  {
    id: 146,
    name_cn: '蒙古',
    name_en: 'Mongolia',
    name_en_complete: null,
    alpha2: 'MN',
    alpha3: 'MNG',
    numeric: 496,
  },
  {
    id: 147,
    name_cn: '黑山',
    name_en: 'Montenegro',
    name_en_complete: 'he Republic of Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    numeric: 499,
    note: 'ISO 3166.1:2006新增',
  },
  {
    id: 148,
    name_cn: '蒙特塞拉特',
    name_en: 'Montserrat',
    name_en_complete: null,
    alpha2: 'MS',
    alpha3: 'MSR',
    numeric: 500,
  },
  {
    id: 149,
    name_cn: '摩洛哥',
    name_en: 'Morocco',
    name_en_complete: 'the Kingdom of Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    numeric: 504,
  },
  {
    id: 150,
    name_cn: '莫桑比克',
    name_en: 'Mozambique',
    name_en_complete: 'the Republic of Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    numeric: 508,
  },
  {
    id: 151,
    name_cn: '缅甸',
    name_en: 'Myanmar',
    name_en_complete: 'the Union of Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    numeric: 104,
  },
  {
    id: 152,
    name_cn: '纳米比亚',
    name_en: 'Namibia',
    name_en_complete: 'the Republic of Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    numeric: 516,
  },
  {
    id: 153,
    name_cn: '瑙鲁',
    name_en: 'Nauru',
    name_en_complete: 'the Republic of Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    numeric: 520,
  },
  {
    id: 154,
    name_cn: '尼泊尔',
    name_en: 'Nepal',
    name_en_complete: 'Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    numeric: 524,
  },
  {
    id: 155,
    name_cn: '荷兰',
    name_en: 'Netherlands (the)',
    name_en_complete: 'the Kingdom of the Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    numeric: 528,
  },
  {
    id: 156,
    name_cn: '荷属安的列斯',
    name_en: 'Netherlands Antilles (the)',
    name_en_complete: null,
    alpha2: 'AN',
    alpha3: 'ANT',
    numeric: 530,
  },
  {
    id: 157,
    name_cn: '新喀里多尼亚',
    name_en: 'New Caledonia',
    name_en_complete: null,
    alpha2: 'NC',
    alpha3: 'NCL',
    numeric: 540,
  },
  {
    id: 158,
    name_cn: '新西兰',
    name_en: 'New Zealand',
    name_en_complete: null,
    alpha2: 'NZ',
    alpha3: 'NZL',
    numeric: 554,
  },
  {
    id: 159,
    name_cn: '尼加拉瓜',
    name_en: 'Nicaragua',
    name_en_complete: 'the Republic of Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    numeric: 558,
  },
  {
    id: 160,
    name_cn: '尼日尔',
    name_en: 'Niger (the)',
    name_en_complete: 'the Republic of the Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    numeric: 562,
  },
  {
    id: 161,
    name_cn: '尼日利亚',
    name_en: 'Nigeria',
    name_en_complete: 'the Federal Republic of Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    numeric: 566,
  },
  {
    id: 162,
    name_cn: '纽埃',
    name_en: 'Niue',
    name_en_complete: 'the Republic of Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    numeric: 570,
  },
  {
    id: 163,
    name_cn: '诺福克岛',
    name_en: 'Norfolk Island',
    name_en_complete: null,
    alpha2: 'NF',
    alpha3: 'NFK',
    numeric: 574,
  },
  {
    id: 164,
    name_cn: '北马里亚纳',
    name_en: 'Northern Mariana Islands (the)',
    name_en_complete: 'the Commonwealth of the Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    numeric: 580,
  },
  {
    id: 165,
    name_cn: '挪威',
    name_en: 'Norway',
    name_en_complete: 'the Kingdom of Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    numeric: 578,
  },
  {
    id: 166,
    name_cn: '阿曼',
    name_en: 'Oman',
    name_en_complete: 'the Sultanate of Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    numeric: 512,
  },
  {
    id: 167,
    name_cn: '巴基斯坦',
    name_en: 'Pakistan',
    name_en_complete: 'the Islamic Republic of Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    numeric: 586,
  },
  {
    id: 168,
    name_cn: '帕劳',
    name_en: 'Palau',
    name_en_complete: 'the Republic of Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    numeric: 585,
  },
  {
    id: 169,
    name_cn: '巴勒斯坦',
    name_en: 'Palestinian Territory (the Occupied)',
    name_en_complete: 'the Occupied Palestinian Territory',
    alpha2: 'PS',
    alpha3: 'PSE',
    numeric: 275,
  },
  {
    id: 170,
    name_cn: '巴拿马',
    name_en: 'Panama',
    name_en_complete: 'the Republic of Panama',
    alpha2: 'PA',
    alpha3: 'PAN',
    numeric: 591,
  },
  {
    id: 171,
    name_cn: '巴布亚新几内亚',
    name_en: 'Papua New Guinea',
    name_en_complete: null,
    alpha2: 'PG',
    alpha3: 'PNG',
    numeric: 598,
  },
  {
    id: 172,
    name_cn: '巴拉圭',
    name_en: 'Paraguay',
    name_en_complete: 'the Republic of Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    numeric: 600,
  },
  {
    id: 173,
    name_cn: '秘鲁',
    name_en: 'Peru',
    name_en_complete: 'the Republic of Peru',
    alpha2: 'PE',
    alpha3: 'PER',
    numeric: 604,
  },
  {
    id: 174,
    name_cn: '菲律宾',
    name_en: 'Philippines (the)',
    name_en_complete: 'the Republic of the Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    numeric: 608,
  },
  {
    id: 175,
    name_cn: '皮特凯恩',
    name_en: 'Pitcairn',
    name_en_complete: null,
    alpha2: 'PN',
    alpha3: 'PCN',
    numeric: 612,
  },
  {
    id: 176,
    name_cn: '波兰',
    name_en: 'Poland',
    name_en_complete: 'the Republic of Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    numeric: 616,
  },
  {
    id: 177,
    name_cn: '葡萄牙',
    name_en: 'Portugal',
    name_en_complete: 'the Portuguese Republic',
    alpha2: 'PT',
    alpha3: 'PRT',
    numeric: 620,
  },
  {
    id: 178,
    name_cn: '波多黎各',
    name_en: 'Puerto Rico',
    name_en_complete: null,
    alpha2: 'PR',
    alpha3: 'PRI',
    numeric: 630,
  },
  {
    id: 179,
    name_cn: '卡塔尔',
    name_en: 'Qatar',
    name_en_complete: 'the State of Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    numeric: 634,
  },
  {
    id: 180,
    name_cn: '留尼汪',
    name_en: 'Réunion',
    name_en_complete: null,
    alpha2: 'RE',
    alpha3: 'REU',
    numeric: 638,
  },
  {
    id: 181,
    name_cn: '罗马尼亚',
    name_en: 'Romania',
    name_en_complete: null,
    alpha2: 'RO',
    alpha3: 'ROU',
    numeric: 642,
  },
  {
    id: 182,
    name_cn: '俄罗斯联邦',
    name_en: 'Russian Federation (the)',
    name_en_complete: 'the Russian Federation',
    alpha2: 'RU',
    alpha3: 'RUS',
    numeric: 643,
  },
  {
    id: 183,
    name_cn: '卢旺达',
    name_en: 'Rwanda',
    name_en_complete: 'the Republic of Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    numeric: 646,
  },
  {
    id: 184,
    name_cn: '圣赫勒拿',
    name_en: 'Saint Helena',
    name_en_complete: null,
    alpha2: 'SH',
    alpha3: 'SHN',
    numeric: 654,
  },
  {
    id: 185,
    name_cn: '圣基茨和尼维斯',
    name_en: 'Saint Kitts and Nevis',
    name_en_complete: null,
    alpha2: 'KN',
    alpha3: 'KNA',
    numeric: 659,
  },
  {
    id: 186,
    name_cn: '圣卢西亚',
    name_en: 'Saint Lucia',
    name_en_complete: null,
    alpha2: 'LC',
    alpha3: 'LCA',
    numeric: 662,
  },
  {
    id: 187,
    name_cn: '圣皮埃尔和密克隆',
    name_en: 'Saint Pierre and Miquelon',
    name_en_complete: null,
    alpha2: 'PM',
    alpha3: 'SPM',
    numeric: 666,
  },
  {
    id: 188,
    name_cn: '圣文森特和格林纳丁斯',
    name_en: 'Saint Vincent and the Grenadines',
    name_en_complete: null,
    alpha2: 'VC',
    alpha3: 'VCT',
    numeric: 670,
  },
  {
    id: 189,
    name_cn: '萨摩亚',
    name_en: 'Samoa',
    name_en_complete: 'the Independent State of Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    numeric: 882,
  },
  {
    id: 190,
    name_cn: '圣马力诺',
    name_en: 'San Marino',
    name_en_complete: 'the Republic of San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    numeric: 674,
  },
  {
    id: 191,
    name_cn: '圣多美和普林西比',
    name_en: 'Sao Tome and Principe',
    name_en_complete: 'the Democratic Republic of Sao Tome and Principe',
    alpha2: 'ST',
    alpha3: 'STP',
    numeric: 678,
  },
  {
    id: 192,
    name_cn: '沙特阿拉伯',
    name_en: 'Saudi Arabia',
    name_en_complete: 'the Kingdom of Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    numeric: 682,
  },
  {
    id: 193,
    name_cn: '塞内加尔',
    name_en: 'Senegal',
    name_en_complete: 'the Republic of Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    numeric: 686,
  },
  {
    id: 194,
    name_cn: '塞尔维亚',
    name_en: 'Serbia',
    name_en_complete: 'the Republic of Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    numeric: 688,
    note: 'ISO 3166.1-2006新增',
  },
  {
    id: 195,
    name_cn: '塞舌尔',
    name_en: 'Seychelles',
    name_en_complete: 'the Republic of Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    numeric: 690,
  },
  {
    id: 196,
    name_cn: '塞拉利昂',
    name_en: 'Sierra Leone',
    name_en_complete: 'the Republic of Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    numeric: 694,
  },
  {
    id: 197,
    name_cn: '新加坡',
    name_en: 'Singapore',
    name_en_complete: 'the Republic of Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    numeric: 702,
  },
  {
    id: 198,
    name_cn: '斯洛伐克',
    name_en: 'Slovakia',
    name_en_complete: 'the Slovak Republic',
    alpha2: 'SK',
    alpha3: 'SVK',
    numeric: 703,
  },
  {
    id: 199,
    name_cn: '斯洛文尼亚',
    name_en: 'Slovenia',
    name_en_complete: 'the Republic of Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    numeric: 705,
  },
  {
    id: 200,
    name_cn: '所罗门群岛',
    name_en: 'Solomon Islands (the)',
    name_en_complete: null,
    alpha2: 'SB',
    alpha3: 'SLB',
    numeric: 90,
  },
  {
    id: 201,
    name_cn: '索马里',
    name_en: 'Somalia',
    name_en_complete: 'the Somali Republic',
    alpha2: 'SO',
    alpha3: 'SOM',
    numeric: 706,
  },
  {
    id: 202,
    name_cn: '南非',
    name_en: 'South Africa',
    name_en_complete: 'the Republic of South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    numeric: 710,
  },
  {
    id: 203,
    name_cn: '南乔治亚岛和南桑德韦奇岛',
    name_en: 'South Georgia and the South Sandwich Islands',
    name_en_complete: null,
    alpha2: 'GS',
    alpha3: 'SGS',
    numeric: 239,
  },
  {
    id: 204,
    name_cn: '西班牙',
    name_en: 'Spain',
    name_en_complete: 'the Kingdom of Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    numeric: 724,
  },
  {
    id: 205,
    name_cn: '斯里兰卡',
    name_en: 'Sri Lanka',
    name_en_complete: 'the Democratic Socialist Republic of Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    numeric: 144,
  },
  {
    id: 206,
    name_cn: '苏丹',
    name_en: 'Sudan (the)',
    name_en_complete: 'the Republic of the Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    numeric: 736,
  },
  {
    id: 207,
    name_cn: '苏里南',
    name_en: 'Suriname',
    name_en_complete: 'the Republic of Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    numeric: 740,
  },
  {
    id: 208,
    name_cn: '斯瓦尔巴岛和扬马延岛',
    name_en: 'Svalbard and Jan Mayen',
    name_en_complete: null,
    alpha2: 'SJ',
    alpha3: 'SJM',
    numeric: 744,
  },
  {
    id: 209,
    name_cn: '斯威士兰',
    name_en: 'Swaziland',
    name_en_complete: 'the Kingdom of Swaziland',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    numeric: 748,
  },
  {
    id: 210,
    name_cn: '瑞典',
    name_en: 'Sweden',
    name_en_complete: 'the Kingdom of Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    numeric: 752,
  },
  {
    id: 211,
    name_cn: '瑞士',
    name_en: 'Switzerland',
    name_en_complete: 'the Swiss Confederation',
    alpha2: 'CH',
    alpha3: 'CHE',
    numeric: 756,
  },
  {
    id: 212,
    name_cn: '叙利亚',
    name_en: 'Syrian Arab Republic (the)',
    name_en_complete: 'the Syrian Arab Republic',
    alpha2: 'SY',
    alpha3: 'SYR',
    numeric: 760,
  },
  {
    id: 213,
    name_cn: '台湾',
    name_en: 'Taiwan (Province of China)',
    name_en_complete: null,
    alpha2: 'TW',
    alpha3: 'TWN',
    numeric: 158,
  },
  {
    id: 214,
    name_cn: '塔吉克斯坦',
    name_en: 'Tajikistan',
    name_en_complete: 'the Republic of Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    numeric: 762,
  },
  {
    id: 215,
    name_cn: '坦桑尼亚',
    name_en: 'Tanzania,United Republic of',
    name_en_complete: 'the United Republic of Tanzania',
    alpha2: 'TZ',
    alpha3: 'TZA',
    numeric: 834,
  },
  {
    id: 216,
    name_cn: '泰国',
    name_en: 'Thailand',
    name_en_complete: 'the Kingdom of Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    numeric: 764,
  },
  {
    id: 217,
    name_cn: '东帝汶',
    name_en: 'Timor-Leste',
    name_en_complete: 'the Democratic Republic of Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    numeric: 626,
    note: 'ISO 3166.1-2006调整了英文名称和字母代码（原代码为TP\\TMP）',
  },
  {
    id: 218,
    name_cn: '多哥',
    name_en: 'Togo',
    name_en_complete: 'the Togolese Republic',
    alpha2: 'TG',
    alpha3: 'TGO',
    numeric: 768,
  },
  {
    id: 219,
    name_cn: '托克劳',
    name_en: 'Tokelau',
    name_en_complete: null,
    alpha2: 'TK',
    alpha3: 'TKL',
    numeric: 772,
  },
  {
    id: 220,
    name_cn: '汤加',
    name_en: 'Tonga',
    name_en_complete: 'the Kingdom of Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    numeric: 776,
  },
  {
    id: 221,
    name_cn: '特立尼达和多巴哥',
    name_en: 'Trinidad and Tobago',
    name_en_complete: 'the Republic of Trinidad and Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    numeric: 780,
  },
  {
    id: 222,
    name_cn: '突尼斯',
    name_en: 'Tunisia',
    name_en_complete: 'the Republic of Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    numeric: 788,
  },
  {
    id: 223,
    name_cn: '土耳其',
    name_en: 'Turkey',
    name_en_complete: 'the Republic of Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    numeric: 792,
  },
  {
    id: 224,
    name_cn: '土库曼斯坦',
    name_en: 'Turkmenistan',
    name_en_complete: null,
    alpha2: 'TM',
    alpha3: 'TKM',
    numeric: 795,
  },
  {
    id: 225,
    name_cn: '特克斯和凯科斯群岛',
    name_en: 'Turks and Caicos Islands (the)',
    name_en_complete: null,
    alpha2: 'TC',
    alpha3: 'TCA',
    numeric: 796,
  },
  {
    id: 226,
    name_cn: '图瓦卢',
    name_en: 'Tuvalu',
    name_en_complete: null,
    alpha2: 'TV',
    alpha3: 'TUV',
    numeric: 798,
  },
  {
    id: 227,
    name_cn: '乌干达',
    name_en: 'Uganda',
    name_en_complete: 'the Republic of Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    numeric: 800,
  },
  {
    id: 228,
    name_cn: '乌克兰',
    name_en: 'Ukraine',
    name_en_complete: null,
    alpha2: 'UA',
    alpha3: 'UKR',
    numeric: 804,
  },
  {
    id: 229,
    name_cn: '阿联酋',
    name_en: 'United Arab Emirates (the)',
    name_en_complete: 'the United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: 784,
  },
  {
    id: 230,
    name_cn: '英国',
    name_en: 'United Kingdom (the)',
    name_en_complete:
      'the United Kingdom of Great Britain and Northern Ireland',
    alpha2: 'GB',
    alpha3: 'GBR',
    numeric: 826,
  },
  {
    id: 231,
    name_cn: '美国',
    name_en: 'United States (the)',
    name_en_complete: 'the United States of America',
    alpha2: 'US',
    alpha3: 'USA',
    numeric: 840,
  },
  {
    id: 232,
    name_cn: '美国本土外小岛屿',
    name_en: 'United States Minor Outlying Islands (the)',
    name_en_complete: null,
    alpha2: 'UM',
    alpha3: 'UMI',
    numeric: 581,
  },
  {
    id: 233,
    name_cn: '乌拉圭',
    name_en: 'Uruguay',
    name_en_complete: 'the Eastern Republic of Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    numeric: 858,
  },
  {
    id: 234,
    name_cn: '乌兹别克斯坦',
    name_en: 'Uzbekistan',
    name_en_complete: 'the Republic of Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    numeric: 860,
  },
  {
    id: 235,
    name_cn: '瓦努阿图',
    name_en: 'Vanuatu',
    name_en_complete: 'the Republic of Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    numeric: 548,
  },
  {
    id: 236,
    name_cn: '委内瑞拉',
    name_en: 'Venezuela',
    name_en_complete: 'the Bolivarian Republic of Venezuela',
    alpha2: 'VE',
    alpha3: 'VEN',
    numeric: 862,
  },
  {
    id: 237,
    name_cn: '越南',
    name_en: 'Viet Nam',
    name_en_complete: 'the Socialist Republic of Viet Nam',
    alpha2: 'VN',
    alpha3: 'VNM',
    numeric: 704,
  },
  {
    id: 238,
    name_cn: '英属维尔京群岛',
    name_en: 'Virgin Islands (British)',
    name_en_complete: 'British Virgin Islands (the)',
    alpha2: 'VG',
    alpha3: 'VGB',
    numeric: 92,
  },
  {
    id: 239,
    name_cn: '美属维尔京群岛',
    name_en: 'Virgin Islands (U.S.)',
    name_en_complete: 'the Virgin Islands of the United States',
    alpha2: 'VI',
    alpha3: 'VIR',
    numeric: 850,
  },
  {
    id: 240,
    name_cn: '瓦利斯和富图纳',
    name_en: 'Wallis and Futuna',
    name_en_complete: 'Wallis and Futuna Islands',
    alpha2: 'WF',
    alpha3: 'WLF',
    numeric: 876,
  },
  {
    id: 241,
    name_cn: '西撒哈拉',
    name_en: 'Western Sahara',
    name_en_complete: null,
    alpha2: 'EH',
    alpha3: 'ESH',
    numeric: 732,
  },
  {
    id: 242,
    name_cn: '也门',
    name_en: 'Yemen',
    name_en_complete: 'the Republic of Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    numeric: 887,
  },
  {
    id: 243,
    name_cn: '赞比亚',
    name_en: 'Zambia',
    name_en_complete: 'the Republic of Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    numeric: 894,
  },
  {
    id: 244,
    name_cn: '津巴布韦',
    name_en: 'Zimbabwe',
    name_en_complete: 'the Republic of Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    numeric: 716,
  },
];
